name: Update Fork Star

on:
  fork:
  watch:
    types:
      - started
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: This repo has x stars y forks
        uses: ouuan/This-repo-has-x-stars-y-forks-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: "Simon-He95's profile with <starCount> stars and <forkCount> forks 🎉"
